#!/bin/sh

# call script with argument 00 or 12
# $ ./getdata 00

if [ -z "${1}" ]; then
  echo please prive an argument
  exit 1
fi

# GFS_SCRIPT_PATH
# basebath for scripts
echo GFS_SCRIPT_PATH=$GFS_SCRIPT_PATH

# GFS_NPZ_DATA
# target path for gfs-data
echo GFS_NPZ_DATA=$GFS_NPZ_DATA

# GFS_JSON_DATA
# target path for gfs json wind-data
echo GFS_JSON_DATA=$GFS_JSON_DATA

echo

DEFAULT_SCRIPT_DIR="~/public_html/scripts/"

if [ ! -z "${GFS_SCRIPT_PATH}" ]; then
  cd $GFS_SCRIPT_PATH
else
  cd $DEFAULT_SCRIPT_DIR
fi

echo "--- getdata start ---";

if [ ! -d "data2" ]; then
  echo "data2 folder does not exist!"
  exit -1
fi

# check lock file
if [ -f .lock ]; then
  echo "locked - exit"
  exit 0
fi

# set lock
touch .lock

# enter data2-folder
cd data2

# log date
date -u

# get date
d=`date -u +%Y%m%d`

if [ "$#" -gt 1 ]; then
  d=$2
fi

python getdatanomads2.py $d $1 || {
  echo gfs err;
  # remove .lock from correct directory
  if [ ! -z "${GFS_SCRIPT_PATH}" ]; then
    cd $GFS_SCRIPT_PATH
  else
    cd $DEFAULT_SCRIPT_DIR
  fi
  rm .lock;
  #
  exit 1;
}

if [ ! -z "${GFS_NPZ_DATA}" ]; then
  mkdir -p ${GFS_NPZ_DATA}
  echo "copy gfs-data to ${GFS_NPZ_DATA}"
  cp -rfp gfs.time gfs-* "${GFS_NPZ_DATA}/"
else
  echo "copy gfs-data to .."
  cp -rfp gfs.time gfs-* ..
fi

# cleanup
rm -rf gfs.time gfs-*

# leave data2/
cd ..

./gfs/generate_wind_data.sh

echo "--- getdata done ---";
# log date
date -u

# remove lock
rm .lock
